# Generated by Django 5.0.4 on 2024-04-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='Unit of measure (e.g., kg, liters, packets)', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity in stock', max_digits=9)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, help_text='Threshold at which to reorder', max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.ingredient')),
            ],
        ),
    ]
